/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleItemPedido;
import controle.modelo.util.Util;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.bean.Bairro;
import modelo.bean.Cliente;
import modelo.bean.ItemPedido;
import modelo.bean.Pedido;
import modelo.bean.Produto;
import modelo.bean.Usuario;
import modelo.conexao.FabricaConexao;
import modelo.dao.ClienteDao;
import modelo.dao.ItemPedidoDao;
import modelo.dao.PedidoDao;
import modelo.dao.ProdutoDao;
import modelo.dao.UsuarioDao;

/**
 *
 * @author vronei
 */
public class TelaPedido extends javax.swing.JInternalFrame {

    int codigoPedido;
    int pedidoCodigo;

    /**
     * Creates new form TelaPedido
     */
    public TelaPedido() throws SQLException {
        initComponents();
        lbusuario.setText("USUÁRIO:" + UsuarioDao.usuario.getNome().toUpperCase());
        preecncherTabela();
        codigoPedido = new PedidoDao().iniciarPedido();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLista = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFcpf = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTendereco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbusuario = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTproduto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTcodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTvalor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSqtde = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtabela = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTtotal = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCancelarPedido = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPedidos = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setDoubleBuffered(true);

        jpLista.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("C.P.F.:");

        jFcpf.setForeground(new java.awt.Color(0, 0, 204));
        try {
            jFcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFcpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFcpf.setSelectionColor(new java.awt.Color(0, 0, 204));
        jFcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFcpfActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jTnome.setEditable(false);
        jTnome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTnome.setForeground(new java.awt.Color(0, 0, 204));

        jLabel3.setText("Endereço:");

        jTendereco.setEditable(false);
        jTendereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTendereco.setForeground(new java.awt.Color(0, 0, 204));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/localizar.gif"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTendereco)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jFcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTnome)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 408, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFcpf)
                    .addComponent(jTnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbusuario.setText("USUÁRIO:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbusuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbusuario)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Codigo Produto:");

        jLabel5.setText("Nome:");

        jTproduto.setEditable(false);
        jTproduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTproduto.setForeground(new java.awt.Color(0, 0, 204));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/localizar.gif"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTcodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTcodigo.setForeground(new java.awt.Color(0, 0, 204));

        jLabel6.setText("Valor:");

        jTvalor.setEditable(false);
        jTvalor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTvalor.setForeground(new java.awt.Color(0, 0, 204));

        jLabel7.setText("Quuantidade:");

        jSqtde.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSqtde.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/novo_registro.gif"))); // NOI18N
        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSqtde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTproduto)
                        .addComponent(jTcodigo)
                        .addComponent(jTvalor)
                        .addComponent(jSqtde))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTtabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Valor", "Qtde", "Sub_Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTtabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTtabela);
        if (jTtabela.getColumnModel().getColumnCount() > 0) {
            jTtabela.getColumnModel().getColumn(0).setResizable(false);
            jTtabela.getColumnModel().getColumn(1).setResizable(false);
            jTtabela.getColumnModel().getColumn(2).setResizable(false);
            jTtabela.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Total do Pedido:");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/gravar_registro.gif"))); // NOI18N
        jButton4.setText("Fechar Pedido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTtotal.setForeground(new java.awt.Color(0, 0, 255));
        jTtotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jTtotal.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        jLabel9.setText("Data de  entrega:");

        btnCancelarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/delete.gif"))); // NOI18N
        btnCancelarPedido.setText("Cancelar Pedido");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                .addComponent(btnCancelarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel8))
                            .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
        );

        jpLista.addTab("Pedido Aberto", jPanel1);

        tbPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbPedidos.setForeground(new java.awt.Color(0, 51, 204));
        tbPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PED.", "STATUS", "DT.ABERTURA", "DT.ENTREGA", "VALOR", "CLIENTE", "VENDEDOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPedidosMouseClicked(evt);
            }
        });
        tbPedidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbPedidosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbPedidos);
        if (tbPedidos.getColumnModel().getColumnCount() > 0) {
            tbPedidos.getColumnModel().getColumn(0).setResizable(false);
            tbPedidos.getColumnModel().getColumn(1).setResizable(false);
            tbPedidos.getColumnModel().getColumn(2).setResizable(false);
            tbPedidos.getColumnModel().getColumn(3).setResizable(false);
            tbPedidos.getColumnModel().getColumn(4).setResizable(false);
            tbPedidos.getColumnModel().getColumn(5).setResizable(false);
            tbPedidos.getColumnModel().getColumn(6).setResizable(false);
        }

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/delete.gif"))); // NOI18N
        btnExcluir.setText("Excluir");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/alterar_registro.gif"))); // NOI18N
        jButton5.setText("Alterar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1175, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );

        jpLista.addTab("Pedido Andamento", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpLista)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpLista)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        buscarClienteCPF();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        buscarProduto();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            adicionarItens();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        fecharPedido();
        try {
            preecncherTabela();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(TelaPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jFcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFcpfActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        if (tbPedidos.getSelectedRow() != -1) {
            Pedido p = new Pedido();
            PedidoDao dao = new PedidoDao();
            int codigoSelecionado = (int) tbPedidos.getValueAt(tbPedidos.getSelectedRow(), 0);
            //dzcen  n n gbvV C ]cv] c } v \bv\ v\   \vc cvvccv///x//   raqsx
            //p = dao.findBy(codigoSelecionado);

            jPanel1.show();
            jFcpf.setText(p.getCliente().getCpf());
            jTnome.setText(p.getCliente().getNome());

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro para alterar");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        // TODO add your handling code here:
        Connection conexao;
        PreparedStatement pstm;
        ResultSet rs;
        try {
            conexao = FabricaConexao.pegaCoonexao();
            pstm = conexao.prepareStatement("select * from pedido inner join itempedido on pedido.codigo=itempedido.pedido inner join produto on itempedido.produto=produto.prodid where pedvalor=?");
            pstm.setInt(1, 0);
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Pedido cancelado");
        } catch (SQLException e) {

        } finally {
            FabricaConexao.fecharConexao();
        }
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    private void tbPedidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPedidosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbPedidosKeyPressed

    private void tbPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPedidosMouseClicked
        // TODO add your handling code here

        if (tbPedidos.getSelectedRow() != -1) {
            Util pegaIdPedido = new Util();

            int id = (int) tbPedidos.getValueAt(tbPedidos.getSelectedRow(), 0);
            pegaIdPedido.setPedidoid(id);
            FrmItens janelaItens = new FrmItens();
            janelaItens.setVisible(true);
            janelaItens.setLocationRelativeTo(null);

            //  System.out.println("codigo: "+pedidoCodigo);
        }
    }//GEN-LAST:event_tbPedidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFcpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSqtde;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTendereco;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTproduto;
    private javax.swing.JTable jTtabela;
    private javax.swing.JFormattedTextField jTtotal;
    private javax.swing.JTextField jTvalor;
    private javax.swing.JTabbedPane jpLista;
    private static javax.swing.JLabel lbusuario;
    private javax.swing.JTable tbPedidos;
    // End of variables declaration//GEN-END:variables

    private void buscarClienteCPF() {
        String cpf = jFcpf.getText().replaceAll("[.-]", "");

        System.err.println("CPF: " + cpf);

        try {
            Cliente c = new ClienteDao().buscarClienteCPF(cpf);

            jTnome.setText(c.getNome());
            jTendereco.setText("Rua: " + c.getRua() + " Numero: " + c.getNumero() + " Bairro: " + c.getBairro().getNome());

        } catch (SQLException ex) {
            Logger.getLogger(TelaPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//fimm

    public void preecncherTabela() throws SQLException {

        DefaultTableModel modelo = (DefaultTableModel) tbPedidos.getModel();
        PedidoDao dao = new PedidoDao();

        modelo.setNumRows(0);

        for (Pedido p : dao.listar()) {

            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyy");
            //String data = df.format(a.getDataNascimento());

            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getStatus(),
                p.getDtPrdido(),
                p.getDtEntrega(),
                p.getValor(),
                p.getUsuario().getNome(),
                p.getCliente().getNome(),});
        }
    }

    private void buscarProduto() {
        int codigo = Integer.parseInt(jTcodigo.getText());
        System.out.println("dddddd " + codigo);
        try {
            Produto p = new ProdutoDao().buscarProduto(codigo);
            if (p == null) {

            } else {
                jTproduto.setText(p.getNome());
                jTvalor.setText(String.valueOf(p.getPreco_venda()));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//ffim

    private void adicionarItens() throws SQLException {

        ControleItemPedido controle = new ControleItemPedido();
        Pedido ped = new Pedido();
        Produto prod = new Produto();

        int codigo = Integer.parseInt(jTcodigo.getText());
        String nome = jTproduto.getText();
        double valor = Double.parseDouble(jTvalor.getText());
        int qtde = Integer.parseInt(String.valueOf(jSqtde.getValue()));
        double subTotal = valor * qtde;
        DefaultTableModel tab = (DefaultTableModel) jTtabela.getModel();
        tab.addRow(new Object[]{codigo, nome, valor, qtde, subTotal});
        jTtotal.setText(String.valueOf(calcularValorPedido()));

        ped.setCodigo(codigoPedido);

        prod.setCodigo(codigo);
        prod.setPreco_venda(valor);
        controle.adcionarItem(prod, ped, qtde, subTotal);

    }//fim

    private double calcularValorPedido() {
        int linha = jTtabela.getRowCount();
        double total = 0;
        for (int i = 0; i < linha; i++) {
            total += Double.parseDouble(String.valueOf(jTtabela.getValueAt(i, 4)));
        }
        return total;
    }//fim

    public void iniciarPedido() {

    }

    private void fecharPedido() {
        Usuario u = new Usuario();
        // UsuarioDao dao =new UsuarioDao();
        u.setId(UsuarioDao.usuario.getId());
        Cliente c = new Cliente();
        c.setCpf(jFcpf.getText().replaceAll("[.-]", ""));
        Pedido p = new Pedido();
        p.setCliente(c);
        p.setUsuario(u);
        p.setValor(Double.parseDouble(jTtotal.getText()));
        p.setDtEntrega(jDateChooser1.getDate());
        try {
            new PedidoDao().salvar(p);
            JOptionPane.showMessageDialog(null, "Pedido Salvo com sucesso !");
        } catch (SQLException ex) {
            System.out.println();
            JOptionPane.showMessageDialog(null, "Erro ao salvar " + ex.getMessage());
        }
    }//im
}
